// GET PRESENTATION PAGE
export const GET_PRESENTATION_LOADING = "GET_PRESENTATION_LOADING";
export const GET_PRESENTATION_CONTENT = "GET_PRESENTATION_CONTENT";
export const GET_PRESENTATION_ERROR="GET_PRESENTATION_ERROR"

// SIGN UP CLIENT

export const POST_SIGNUP_CLIENT_LOADING ="POST_SIGNUP_CLIENT_LOADING"
export const POST_SIGNUP_CLIENT="POST_SIGNUP_CLIENT"
export const POST_SIGNUP_CLIENT_ERROR="POST_SIGNUP_CLIENT_ERROR"

// SIGN UP TRASNPORTER

export const POST_SIGNUP_TRANSPORTER_LOADING ="POST_SIGNUP_TRANSPORTER_LOADING"
export const POST_SIGNUP_TRANSPORTER="POST_SIGNUP_TRANSPORTER"
export const POST_SIGNUP_TRANSPORTER_ERROR="POST_SIGNUP_TRANSPORTER_ERROR"


// LOGIN

export const POST_LOGIN_LOADING ="POST_LOGIN_LOADING"
export const POST_LOGIN="POST_LOGIN"
export const POST_LOGIN_ERROR="POST_LOGIN_ERROR"

// GET 8 ADS

export const GET_8_ADS_LOADING ="GET_8_ADS_LOADING";
export const GET_8_ADS="GET_8_ADS"
export const GET_8_ADS_ERROR="GET_8_ADS_ERROR"


// SEARCH ADS FROM /TO

export const GET_ADS_FROM_TO_LOADING ="GET_ADS_FROM_TO_LOADING";
export const GET_ADS_FROM_TO="GET_ADS_FROM_TO"
export const GET_ADS_FROM_TO_ERROR="GET_ADS_FROM_TO_ERROR"


// GET PRODUCTS CLASSIFCATIONS
export const GET_PRODUCTS_CLASSES_LOADING ="GET_PRODUCTS_CLASSES_LOADING";
export const GET_PRODUCTS_CLASSES="GET_PRODUCTS_CLASSES"
export const GET_PRODUCTS_CLASSES_ERROR="GET_PRODUCTS_CLASSES_ERROR"
