// GET PRESENTATION PAGE
export const GET_PRESENTATION_LOADING = "GET_PRESENTATION_LOADING";
export const GET_PRESENTATION_CONTENT = "GET_PRESENTATION_CONTENT";
export const GET_PRESENTATION_ERROR="GET_PRESENTATION_ERROR"

// SIGN UP CLIENT

export const POST_SIGNUP_CLIENT_LOADING ="POST_SIGNUP_CLIENT_LOADING"
export const POST_SIGNUP_CLIENT="POST_SIGNUP_CLIENT"
export const POST_SIGNUP_CLIENT_ERROR="POST_SIGNUP_CLIENT_ERROR"

// SIGN UP TRASNPORTER

export const POST_SIGNUP_TRANSPORTER_LOADING ="POST_SIGNUP_TRANSPORTER_LOADING"
export const POST_SIGNUP_TRANSPORTER="POST_SIGNUP_TRANSPORTER"
export const POST_SIGNUP_TRANSPORTER_ERROR="POST_SIGNUP_TRANSPORTER_ERROR"


// LOGIN

export const POST_LOGIN_LOADING ="POST_LOGIN_LOADING"
export const POST_LOGIN="POST_LOGIN"
export const POST_LOGIN_ERROR="POST_LOGIN_ERROR"

// GET 8 ADS

export const GET_8_ADS_LOADING ="GET_8_ADS_LOADING";
export const GET_8_ADS="GET_8_ADS"
export const GET_8_ADS_ERROR="GET_8_ADS_ERROR"


// SEARCH ADS FROM /TO

export const GET_ADS_FROM_TO_LOADING ="GET_ADS_FROM_TO_LOADING";
export const GET_ADS_FROM_TO="GET_ADS_FROM_TO"
export const GET_ADS_FROM_TO_ERROR="GET_ADS_FROM_TO_ERROR"


// GET PRODUCTS CLASSIFCATIONS
export const GET_PRODUCTS_CLASSES_LOADING ="GET_PRODUCTS_CLASSES_LOADING";
export const GET_PRODUCTS_CLASSES="GET_PRODUCTS_CLASSES"
export const GET_PRODUCTS_CLASSES_ERROR="GET_PRODUCTS_CLASSES_ERROR"

// POST AD
export const POST_AD_LOADING ="POST_AD_LOADING";
export const POST_AD="POST_AD"
export const POST_AD_ERROR="POST_AD_ERROR"

// GET AD BY ID
export const GET_AD_BY_ID_LOADING ="GET_AD_BY_ID_LOADING"
export const GET_AD_BY_ID ="GET_AD_BY_ID"
export const GET_AD_BY_ID_ERROR ="GET_AD_BY_ID_ERROR"


// CREATE REQUEST DELIVERY

export const POST_CREATE_REQUEST_DELIVERY = "POST_CREATE_REQUEST_DELIVERY"
export const POST_CREATE_REQUEST_DELIVERY_LOADING="POST_CREATE_REQUEST_DELIVERY_LOADING"
export const POST_CREATE_REQUEST_DELIVERY_ERROR="POST_CREATE_REQUEST_DELIVERY_ERROR"

// MODIFY REQUEST DELIVERY STATUS

export const MODIFY_CREATE_REQUEST_DELIVERY = "MODIFY_CREATE_REQUEST_DELIVERY"
export const MODIFY_CREATE_REQUEST_DELIVERY_LOADING="MODIFY_CREATE_REQUEST_DELIVERY_LOADING"
export const MODIFY_CREATE_REQUEST_DELIVERY_ERROR="MODIFY_CREATE_REQUEST_DELIVERY_ERROR"

// LOGOUT

export const LOGOUT ="LOGOUT"


// GET USER DETAILS

export const GET_USER_DETAILS_LOADING="GET_USER_DETAILS_LOADING"
export const GET_USER_DETAILS="GET_USER_DETAILS"
export const GET_USER_DETAILS_ERROR="GET_USER_DETAILS_ERROR"

// GET PROFILE DETAILS

export const GET_PROFILE_DETAILS_LOADING="GET_PROFILE_DETAILS_LOADING"
export const GET_PROFILE_DETAILS="GET_PROFILE_DETAILS"
export const GET_PROFILE_DETAILS_ERROR="GET_PROFILE_DETAILS_ERROR"
